#!/bin/bash
exename=$(basename $0)
backup=~/configbackup
echo $exename
case $1 in
    copy)
cp -r ~/shell/ $backup
cp -r ~/.vim $backup
cp ~/.vimrc $backup
cp ~/.tmux.conf $backup
cp -r ~/.muttrc $backup/mail
cp -r ~/.esmtprc $backup/mail
cp -r ~/.procmailrc $backup/mail
cp -r ~/.fetchmailrc $backup/mail
cp -r ~/.mailcap $backup/mail
cp -r ~/.w3m $backup/
        ;;
    clone)
	git clone https://github.com/adambynes/configbackup.git
        ;;
    add)
	cd $backup; 
	git checkout ./vim/.netrwhist
	git add -u .; git commit -m "`date`"
        ;;
 
    *)
        ;;
esac
